import { DefaultTheme } from "styled-components";
import { PokemonType } from "types/PokemonType";

export const theme: DefaultTheme = {
  colors: {
    type: {
      [PokemonType.Bug]: "#8CB230",
      [PokemonType.Dark]: "#58575F",
      [PokemonType.Dragon]: "#0F6AC0",
      [PokemonType.Electric]: "#EED535",
      [PokemonType.Fairy]: "#ED6EC7",
      [PokemonType.Fighting]: "#D04164",
      [PokemonType.Fire]: "#FD7D24",
      [PokemonType.Flying]: "#748FC9",
      [PokemonType.Ghost]: "#556AAE",
      [PokemonType.Grass]: "#62B957",
      [PokemonType.Ground]: "#DD7748",
      [PokemonType.Ice]: "#61CEC0",
      [PokemonType.Normal]: "#9DA0AA",
      [PokemonType.Poison]: "#A552CC",
      [PokemonType.Psychic]: "#EA5D60",
      [PokemonType.Rock]: "#BAAB82",
      [PokemonType.Steel]: "#417D9A",
      [PokemonType.Water]: "#4A90DA",
    },
    background: {
      type: {
        [PokemonType.Bug]: "#8BD674",
        [PokemonType.Dark]: "#6F6E78",
        [PokemonType.Dragon]: "#7383B9",
        [PokemonType.Electric]: "#F2CB55",
        [PokemonType.Fairy]: "#EBA8C3",
        [PokemonType.Fighting]: "#EB4971",
        [PokemonType.Fire]: "#FFA756",
        [PokemonType.Flying]: "#83A2E3",
        [PokemonType.Ghost]: "#8571BE",
        [PokemonType.Grass]: "#8BBE8A",
        [PokemonType.Ground]: "#F78551",
        [PokemonType.Ice]: "#91D8DF",
        [PokemonType.Normal]: "#B5B9C4",
        [PokemonType.Poison]: "#9F6E97",
        [PokemonType.Psychic]: "#FF6568",
        [PokemonType.Rock]: "#D4C294",
        [PokemonType.Steel]: "#4C91B2",
        [PokemonType.Water]: "#58ABF6",
      },
    },
    text: {
      white: "#fff",
      black: "#17171B",
      grey: "#747476",
      number: "rgba(23, 23, 27, 0.6)",
    },
  },
};
